-- SQL Commands to Create Bets Table Columns
-- Run these in Supabase SQL Editor

-- First, make sure id is set as primary key and auto-increment
ALTER TABLE bets 
ADD COLUMN IF NOT EXISTS id SERIAL PRIMARY KEY;

-- Add all the bet columns
ALTER TABLE bets 
ADD COLUMN IF NOT EXISTS "user" TEXT,
ADD COLUMN IF NOT EXISTS game TEXT,
ADD COLUMN IF NOT EXISTS bet_type TEXT,
ADD COLUMN IF NOT EXISTS stake NUMERIC,
ADD COLUMN IF NOT EXISTS team TEXT,
ADD COLUMN IF NOT EXISTS spread NUMERIC,
ADD COLUMN IF NOT EXISTS total NUMERIC,
ADD COLUMN IF NOT EXISTS direction TEXT,
ADD COLUMN IF NOT EXISTS no_juice BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS result TEXT,
ADD COLUMN IF NOT EXISTS settled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS profit NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS payout NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS created_at TEXT,
ADD COLUMN IF NOT EXISTS settled_at TEXT,
ADD COLUMN IF NOT EXISTS final_score TEXT;

